name = "AtomsSymmetryBase"
uuid = "f8da13d3-e23d-4baa-ad2c-52e8301f10f3"
authors = ["Jae-Mo Lihm <jaemolim96@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Spglib = "f761d5c5-86db-4880-b97f-9680a7cccfb5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
